#pragma once

#include "Misc/DisableWarningMacros.h"

DISABLE_WARNING_PUSH
DISABLE_WARNING_UNINIT_VALUE
DISABLE_WARNING_NOEXCEPT
DISABLE_WARNING_ARITHMETIC_OVERFLOW

#include <toml11/toml.hpp>

DISABLE_WARNING_POP