codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2


coverage:
  precision: 2
  round: down
  range: "90...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "Refureku/Library/Tests/Include/*"
  - "Refureku/Library/Tests/Include/**/*"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no